<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GFX.BulletSharp" Version="1.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.GLControl" Version="4.0.2" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LibGFX">
      <HintPath>..\..\LibGFX\LibGFX\bin\Debug\net8.0\LibGFX.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>