using LibGFX.Core;
using LibGFX.Graphics.Lights;
using LibGFX.Graphics.Materials;
using LibGFX.Graphics.Shader;
using LibGFX.Graphics.Shapes;
using LibGFX.Math;
using OpenTK.Graphics.OpenGL4;
using OpenTK.Mathematics;
using OpenTK.Windowing.Desktop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Rect = LibGFX.Math.Rect;

namespace LibGFX.Graphics
{
    public interface IRenderDevice
    {
        void Init(IGLFWGraphicsContext context);
        void SetContext(IGLFWGraphicsContext context);
        IGLFWGraphicsContext GetContext();
        void Init(Window window);
        void Dispose();
        void MakeCurrent();
        void SwapBuffers();
        void UseVsync(bool value);
        void SetDepthMask(bool value);
        bool IsDepthTestEnabled();
        void SetDepthTest(bool value);
        void EnableDepthTest();
        void DisableDepthTest();
        void EnableAlphaBlend();
        void EnableAdditiveBlend();
        void EnableMultiplicativeBlend();
        void EnableScreenBlend();
        (int srcFactor, int dstFactor) GetCurrentBlendMode();
        void SetBlendMode(int srcFactor, int dstFactor);
        void ResetBlendMode();
        void DisableBlend();
        void SetViewport(Viewport viewport);
        Viewport GetViewport();
        void SetViewMatrix(Matrix4 matrix);
        void SetProjectionMatrix(Matrix4 matrix);
        Matrix4 GetViewMatrix();
        Matrix4 GetProjectionMatrix();
        void Clear(RenderFlags.ClearFlags clearFlags);
        void ClearColor(float r, float g, float b, float a);
        void Flush();
        void BindRenderTarget(IRenderTarget renderTarget); 
        void UnbindRenderTarget();
        int GetCurrentRenderTargetID();
        Vector2i GetRenderTargetSize(RenderTarget2D renderTarget);
        byte[] GetRenderTargetData(RenderTarget2D renderTarget);
        byte[] GetRenderTargetData(RenderTarget2D renderTarget, int width, int height);
        int GetFramebufferIndex();
        void BuildShaderProgram(ShaderProgram shaderProgram);
        void DisposeShaderProgram(ShaderProgram shaderProgram);
        void AddShaderProgram(String name, ShaderProgram shaderProgram);
        void AddShape(Shape shape);
        Shape GetShape(String name);
        void InitShape(Shape shape);
        void DrawShape(Shape shape);
        void DisposeShape(Shape shape);
        bool ExistsShaderProgram(String name);
        ShaderProgram GetShaderProgram(String name);
        void BindShaderProgram(ShaderProgram shaderProgram);
        void UnbindShaderProgram();
        int GetUniformLocation(int program, String name);
        void LoadTexture(Texture texture);
        void LoadTexture(Texture texture, TextureOptions textureOptions);
        void LoadCubemap(Cubemap cubemap);
        void DisposeTexture(Texture texture);
        void DisposeCubemap(Cubemap cubemap);
        void DrawRenderTarget(RenderTarget2D renderTarget);
        void DrawLine(Vector3 start, Vector3 end, Vector4 color);
        void DrawRect(Math.Rect rect, Vector4 color, float borderWidth = 1.0f, float rotation = 0.0f);
        void FillRect(Math.Rect rect, Vector4 color, float rotation = 0.0f);
        void DrawRect3D(Transform transform, Vector4 color, float borderWidth = 1.0f);
        void FillRect3D(Transform transform, Vector4 color);
        void DrawTexture(Transform transform, Texture texture, Vector4 color);
        void DrawTexture(Transform transform, int textureId, Vector4 color);
        void DrawTexture(Transform transform, int textureId, Vector4 color, Vector4 uvTransform);
        void DrawTexture(Transform transform, int textureId, Vector4 color, Vector4 uvTransform, Vector2 uvScale);
        void DrawCubemap(Transform transform, Cubemap cubemap, Vector4 color);
        void DrawVertexArray(Transform transform, int vertexBuffer, int vertexCount, RenderFlags.PrimitiveTypes primitiveTypes);
        Font LoadFont(String path, int fontsize = 48);
        void DrawString2D(String text, Vector2 position, Font font, Vector4 color, float scale = 1.0f, FontAlignment alignment = FontAlignment.BottomLeft);
        void DisposeFont(Font font);
        void LoadMesh(Mesh mesh);
        void DrawMesh(Transform transform, Mesh mesh, IMaterial material);
        void DisposeMesh(Mesh mesh);
        void LoadInstanceContainer(RenderInstanceContainer container);
        void BindMeshForInstance(RenderInstanceContainer container, Mesh mesh);
        void LoadInstances(RenderInstanceContainer container);
        int AddRenderInstance(RenderInstanceContainer container, Transform transform);
        void UpdateInstance(RenderInstanceContainer container, int instanceIndex);
        void DrawInstances(RenderInstanceContainer container, IMaterial material);
        void DisposeInstanceContainer(RenderInstanceContainer container);
        void AddLightSource(string name, Light light);
        void RemoveLightSource(string name);
        IEnumerable<Light> GetAllLightSources();
        T GetLightSource<T>() where T : Light;
        int CreateBuffer();
        int CreateVertexBuffer<T>(T[] data, bool dynamic = false) where T : unmanaged;
        int CreateElementBuffer(int[] data, bool dynamic = false);
        void BindVertexBuffer(int buffer);
        void BindElementBuffer(int buffer);
        void SetVertexBufferData<T>(int buffer, T[] data, bool dynamic = false) where T : unmanaged;
        void SetElementBufferData(int buffer, int[] data, bool dynamic = false);
        void UpdateVertexBufferData<T>(int buffer, T[] data, int offset) where T : unmanaged;
        void UpdateElementBufferData(int buffer, int[] data, int offset);
        void DisposeBuffer(int buffer);
        void BindShaderStorageBuffer(int binding, int buffer);
        void UnbindShaderStorageBuffer(int binding);
        int CreateVertexArray();
        void DisposeVertexArray(int value);
        void BindVertexArray(int value);
        void EnableVertexArrayAttribute(int index);
        void SetVertexArrayAttribute(int index, int size, RenderFlags.RenderDataTypes type, bool normalized, int stride, nint pointer);
        void PrepareShader(String location, bool value);
        void PrepareShader(String location, float value);
        void PrepareShader(String location, int value);
        void PrepareShader(String location, Vector2 value);
        void PrepareShader(String location, Vector3 value);
        void PrepareShader(String location, Vector4 value);
        void PrepareShader(String location, bool transpose, Matrix4 value);
        void PrepareShader(String location, int count, float[] value);
        void PrepareShaderVec2Array(String location, int count, float[] value);
        void PrepareShaderVec3Array(String location, int count, float[] value);
        void PrepareShaderVec4Array(String location, int count, float[] value);
        void PrepareShader(String uniformName, bool transpose, Matrix4[] matrices);
        void PrepareShader(String location, TextureUnit textureUnit, int value);
        void PrepareShader(String location, TextureUnit textureUnit, Texture texture);
        void PrepareShader(String location, int textureUnit, int value);
        void PrepareShader(String location, int textureUnit, Texture texture);
        void PrepareShader(String location, int textureUnit, Cubemap cubemap);
        int GetError();
        public int GenFramebuffer();
        public void BindFramebuffer(RenderFlags.GFXFramebufferTarget target, int framebufferId);
        public int GenTexture();
        public void BindTexture(RenderFlags.GFXTextureTarget target, int unit);
        public void ActiveTexture(int unit);
        public void TexImage2D(RenderFlags.GFXTextureTarget target, int level, RenderFlags.ColorFormatHint internalFormat, int width, int height, int border, RenderFlags.ColorFormatLayout format, RenderFlags.ColorFormatType type, IntPtr data);
        public void TexParameter(RenderFlags.GFXTextureTarget target, RenderFlags.GFXTextureParameterName pname, RenderFlags.TextureFilterMode param);
        public void TexParameter(RenderFlags.GFXTextureTarget target, RenderFlags.GFXTextureParameterName pname, RenderFlags.TextureWrapMode param);
        public void TexParameter(RenderFlags.GFXTextureTarget target, RenderFlags.GFXTextureParameterName pname, Vector4 value);
        public void TexParameter(RenderFlags.GFXTextureTarget target, RenderFlags.GFXTextureParameterName pname, float[] value);
        public void FramebufferTexture2D(RenderFlags.GFXFramebufferTarget target, RenderFlags.GFXFramebufferAttachment attachment, RenderFlags.GFXTextureTarget textarget, int texture, int level);
        public void DrawBufferMode(RenderFlags.RenderBufferMode mode);
        public void ReadBufferMode(RenderFlags.RenderBufferMode mode);
        public int GenRenderbuffer();
        public void BindRenderbuffer(RenderFlags.GFXRenderbufferTarget target, int renderbuffer);
        public void RenderbufferStorageMultisample(RenderFlags.GFXRenderbufferTarget target, int samples, RenderFlags.GFXRenderbufferStorage storage, int width, int height);
        public void RenderbufferStorage(RenderFlags.GFXRenderbufferTarget target, RenderFlags.GFXRenderbufferStorage storage, int width, int height);
        public void FramebufferRenderbuffer(RenderFlags.GFXFramebufferTarget target, RenderFlags.GFXFramebufferAttachment attachment, RenderFlags.GFXRenderbufferTarget renderbuffertarget, int renderbuffer);
        public RenderFlags.GFXFramebufferErrorCode CheckFramebufferStatus(RenderFlags.GFXFramebufferTarget target);
        public void DeleteFramebuffer(int framebuffer);
        public void DeleteTexture(int texture);
        public void DeleteRenderbuffer(int renderbuffer);

        void CullFrontFace();
        void CullBackFace();
    }
}
